### PR TITLE
Add docset feed link

### PR DESCRIPTION
**Pull request by cvogt**
review by @szeiger

### CODE REVIEW

**Comment by d6y** [comment]
@cvogt @szeiger This works for me in Dash:

dash1

dash2

That gives users the reference manual material. We can suggest Dash users also do Dash > Downloads > Scaladoc > and search for slick to get the scaladoc API installed. That gives...

dash3
 
So looks good to me to merge (after fixing up the conflict).

**Comment by szeiger** [comment]
I don't use Dash so I'll defer the decision to @d6y

**Comment by d6y** [comment]
The problem I see with this is keeping it up-to-date with Slick releases.  The page is currently 404-ing, but as there's no specific demand for this, maybe that's ok. And I'll close this PR without merge. @cvogt ok with that?

**Comment by cvogt** [comment]
ok!

**Pull request closed without merging**
