### PR TITLE
Add note about sponsors

### PR DESCRIPTION
**Pull request by cvogt**
cc @szeiger

### CODE REVIEW

**Comment by cvogt** [comment]
as agreed upon with @adamw

**Comment by adamw** [comment]
One minor correction, the Lightbend logo on http://slick.lightbend.com/community/ seems a bit too large ;)

**Comment by cvogt** [comment]
wow, good point. how did that happen :)? Will fix

**Comment by cvogt** [comment]
fix commited

**Comment by adamw** [comment]
looks good :)

**Pull request merged**
