### PR TITLE
Update copyright date

### PR DESCRIPTION
**Pull request by rasummer**
Update copyright date

### CODE REVIEW

**Comment by nafg** [comment]
I'm not even sure what it should say. Lightbend isn't maintaining it now.

**Comment by nafg** [comment]
Hi, should Lightbend be the copyright holders for new code? They haven't been maintaining it for eons.

**Comment by rasummer** [comment]
I can check for you.

**Comment by rasummer** [comment]
@nafg I've checked with the team, the main issue for us is to have the copyright year updated to 2024. So how about using `&copy; 2011 - 2024, The Slick committers` instead of Lightbend.

**Pull request merged**
