### PR TITLE
Rasummer/update skin

### PR DESCRIPTION
**Pull request by rasummer**
@szeiger I've made my first pass at the website. Could you be kind enough to take a look and see if I've missed any parts of the site. I've tested on my Mac, but haven't been able to test on Windows/Internet Explorer etc. Do we have a staging site, or can we generate a working static copy that I can push up to a server?

Rich

homepage
community
docs

### CODE REVIEW

**Comment by szeiger** [comment]
Hey Richard, I haven't had the time to look at this yet. Are you in the office later today or tomorrow? Maybe we could do this together.

**Comment by rasummer** [comment]
Sure, let's grab sometime today, as I'm not in the office tomorrow

**Comment by d6y** [comment]
@rasummer has this PR been over taken by the rebrand to Lightbend, and should we now close this?

**Comment by rasummer** [comment]
Yes we can close this

**Pull request closed without merging**
