### PR TITLE
Add Essential Slick

### PR DESCRIPTION
**Pull request by d6y**
This PR adds reference to _Essential Slick_

It looks like this:

documentation slick 2015-12-04 10-11-23

Apologies: my editor has also trimmed some trailing white space.

Feedback welcome.

BTW, the site was easy to edit using docker (machine, in my case):

```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 4000:4000 jekyll/jekyll jekyll s --watch --baseurl '' --force_polling
```

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @d6y,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cvogt** [comment]
I am ok with this. Any objections @szeiger ?

**Comment by hepin1989** [comment]
@d6y haha,better with a special offer here:)

**Comment by szeiger** [comment]
LGTM. @cvogt, when can we add your book to that list? :)

**Comment by cvogt** [comment]
@szeiger that's on ice. Other things have taken priority. Watch my NEScala talk live stream ;).

**Pull request merged**
