### PR TITLE
Add links to effect types article and example

### PR DESCRIPTION
**Pull request by dwestheide**
Add links to article on restricting Slick effect types and to the example project.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @dwestheide,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by cvogt** [comment]
@dwestheide we still need your signature :)

**Comment by dwestheide** [comment]
@cvogt Sorry, been a bit busy the last few days. Signed the agreement now. :)

**Comment by d6y** [comment]
👍 LGTM

**Pull request merged**
